name: CI

permissions:
  contents: read

on:
  pull_request:
  push:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    env:
#RUST_VERSION
      RUST_VERSION: 1.90.0
#RUST_VERSION
    strategy:
      matrix:
        include:
#VERSIONS
          - name: trixie
            variant: trixie
          - name: windowsservercore-1809.17763-msvc
            variant: windowsservercore-1809/msvc
          - name: windowsservercore-1809.17763-gnu
            variant: windowsservercore-1809/gnu
#VERSIONS
    name: ${{ matrix.name }}
    steps:
      - uses: actions/checkout@v5
      - run: git clone https://github.com/docker-library/official-images.git ~/official-images
      - run: docker build -t rust:$RUST_VERSION-${{ matrix.name }} stable/${{ matrix.variant }}
      - run: ~/official-images/test/run.sh rust:$RUST_VERSION-${{ matrix.name }}
      - run: docker images